### ISSUE TITLE
Linux Mint Possible? (Ansible scripts)

### ISSUE THREAD

**Issue by jfeeney100** [yusefnapora/pixelbook-linux#12]
Hi,

Thank you for all the great work you have done on this project! I know the Ansible scripts were written for use under Ubuntu 19.04, however, I was curious about running under Linux Mint  19.01 (which is basically Ubuntu 18.04). I tried running the Ansible script and after providing the alternate key assignments for the search key and assistant key I get the following error:

TASK [common : install OS packages] ***************************************************************************
fatal: [localhost]: FAILED! => {"reason": "Unable to retrieve file contents\nCould not find or access '/home/john/pixelbook-linux/ansible/packages-Linux Mint.yml'"}
	to retry, use: --limit @/home/john/pixelbook-linux/ansible/playbook.retry

Any ideas or help would be great as I would love to run Mint.

**Comment by flantel** [comment]
Hi,

You could try editing ansible/roles/common/tasks/main.yml and change `{{ ansible_distribution }}` to `Ubuntu`

**Comment by jfeeney100** [comment]
Hi flantel,

Thank you for the suggestion. I will give that a try this afternoon.

**Comment by jfeeney100** [comment]
update: Editing the main.yml file was a success in getting the script to run in Linux Mint 19.1. However, after completing the installation and rebooting, sound is still not working, and touchpad remains the same.

**Comment by flantel** [comment]
@jfeeney100 A couple of things to check:

1. Check if you have xserver-xorg-input-synaptics installed, and if so, remove it - I am not sure about Mate, but XFCE installs this and if it is present then the proper touchpad driver does not get used.
2. Run `uname -r` and if it is not 4.4.178chromium-g4245c5e1 then try removing any other kernels you have installed, or change grub to use 4.4.178chromium-g4245c5e1 as the default.

Hope this helps.

**Comment by jfeeney100** [comment]
@flantel 

Thank you for the reply! 

1. Yes, I do have xserver-xorg-input-synaptics installed. I will be sure to remove before giving the script another go.
2. I will be sure to verify the kernel and remove other instances.

This is fantastic information, thank you. I will give this another shot this evening and report results.

**Comment by flantel** [comment]
You should not need to re-run the Ansible - a reboot should suffice!

I hope it works for you. Love pure Linux in my Pixelbook!

**Comment by jfeeney100** [comment]
@flantel 
So, I'm making progress. Touchpad issue is resolved now by using your suggestion of removing synaptics input. And, backlight control now works with the slider. However, I have an issue with sound now. I don't have any sound and running eve-audio-ctl.py returns:

john@pixelbook:~$ eve-audio-ctl.py
Traceback (most recent call last):
  File "/usr/local/bin/eve-audio-ctl.py", line 277, in <module>
    main()
  File "/usr/local/bin/eve-audio-ctl.py", line 258, in main
    cras = CrasClient()
  File "/usr/local/bin/eve-audio-ctl.py", line 73, in __init__
    self.refresh_status()
  File "/usr/local/bin/eve-audio-ctl.py", line 83, in refresh_status
    output = self._cras()
  File "/usr/local/bin/eve-audio-ctl.py", line 77, in _cras
    proc = subprocess.run(cmd, capture_output=True, encoding='utf-8')
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

Additionally, eve-keyboard-brightness.sh does not appear to be present in usr/local/bin either.


uname -r confirms I am running the chromium specific Kernel: 4.4.178chromium-g4245c5e1

Any ideas why I would getting these errors?

**Comment by jfeeney100** [comment]
Update: I ran the ansible script again and was able to get eve-keyboard-brightness.sh installed and working from /usr/local/bin.

The only thing left to resolve is the sound issue:

john@pixelbook:~$ eve-audio-ctl.py
Traceback (most recent call last):
File "/usr/local/bin/eve-audio-ctl.py", line 277, in
main()
File "/usr/local/bin/eve-audio-ctl.py", line 258, in main
cras = CrasClient()
File "/usr/local/bin/eve-audio-ctl.py", line 73, in init
self.refresh_status()
File "/usr/local/bin/eve-audio-ctl.py", line 83, in refresh_status
output = self._cras()
File "/usr/local/bin/eve-audio-ctl.py", line 77, in _cras
proc = subprocess.run(cmd, capture_output=True, encoding='utf-8')
File "/usr/lib/python3.6/subprocess.py", line 423, in run
with Popen(*popenargs, **kwargs) as process:
TypeError: init() got an unexpected keyword argument 'capture_output'
